controllers/NotebookController.php
<?php

namespace app\controllers;
use PDO;
class NotebookController extends \yii\web\Controller
{
	public function actionGenerateKeys()
	{

		$data = 'plaintext data goes here';

		// Encrypt the data to $encrypted using the public key
		openssl_public_encrypt($data, $encrypted, $pubKey);

		// Decrypt the data using the private key and store the results in $decrypted
		openssl_private_decrypt($encrypted, $decrypted, $privKey);

		echo $decrypted;
	}
	public function actionMyNotes() 
	{		
		/**
		 * We use custom session tracking, not Yii2 RBAC or whatever.
		 * Keep it simple. We have our own custom login page (keeping the Yii2 one - but for other purposes).
		 *
		 * Since all notes are forever encrypted, the worst could be a breach of metadata anyway.
		 * Plus, we will enforce HTTPS somewhere down the line.
		*/		
		if (empty(\Yii::$app->session['logged_in']['nu_email']))
		{
			return $this->render("my-notes-login");
		}
		else
		{
			$notes = \Yii::$app->db->createCommand("SELECT * FROM notebook_page WHERE pg_owner = ".\Yii::$app->session['logged_in']['nu_id'])->queryAll();
			return $this->render("my-notes",[
				'notes' => $notes,
			]);
		}
	}
	public function actionAddNote()
	{
		$handles = \Yii::$app->db->createCommand("SELECT nu_id,nu_handle FROM notebook_user ORDER BY nu_handle ASC")->queryAll();
		
		return $this->render("add-note",[
			'handles' => $handles,
		]);
	}
	public function actionAjax()
	{
		switch($_POST['action'])
		{
			case "register":
			/**
			 * Already registered?
			*/
			$cmd = \Yii::$app->db->createCommand("SELECT nu_id FROM notebook_user WHERE nu_email = :email OR nu_handle = :handle LIMIT 1");
			$cmd->bindValue(":handle", $_POST['nu_handle'], PDO::PARAM_STR);
			$cmd->bindValue(":email",  $_POST['nu_email'],  PDO::PARAM_STR);
			if (!empty($cmd->queryOne()))
			{
				die("0");
			}
			/**
			 * Create a key pair based on the data sent by registrant.
			*/
			$hsh = \Yii::$app->getSecurity()->generatePasswordHash($_POST['nu_password']);
			$cfg = [
				"digest_alg"       => "sha512",
				"private_key_bits" => 4096,
				"private_key_type" => OPENSSL_KEYTYPE_RSA,
			];
			
			$res = openssl_pkey_new($cfg); 
			
			// openssl_pkey_export($res, $prv, !empty($_POST['password'])?$_POST['password']:'Yolanda'); // We don't want to enable pw protected pkeys this moment.
			
			openssl_pkey_export($res, $prv);
				   
			$pub = openssl_pkey_get_details($res);
			$pub = $pub["key"];			
				
			$sql = "INSERT INTO notebook_user (nu_handle, nu_password, nu_email, nu_pub, nu_created) VALUES (:handle, :passwd, :email, :pbkey, :today)";

			$cmd = \Yii::$app->db->createCommand($sql);
			$cmd->bindValue(":handle", $_POST['nu_handle'], PDO::PARAM_STR);
			$cmd->bindValue(":passwd", $hsh,  PDO::PARAM_STR);
			$cmd->bindValue(":email",  $_POST['nu_email'],  PDO::PARAM_STR);
			$cmd->bindValue(":pbkey",  $pub,                PDO::PARAM_STR);
			$cmd->bindValue(":today",  date('Y-m-d H:i:s'), PDO::PARAM_STR);

			if ($cmd->execute())
			{
				die($prv);
			}	
			else die('<span class="error">Could not create record.</span>');
			break;
			
			case "decrypt":
			if (!empty($_POST['pg_id']) && !empty($_POST['private_key']))
			{
				die(self::decryptMessage($_POST['pg_id'],$_POST['private_key']));
			}
			else 
			{
				if (empty($_POST['pg_id']))			die('No note specified!');
				if (empty($_POST['private_key']))	die('No key supplied!');
			}
			break;
			
			case "add_note":
			if (!empty($_POST['nu_handle'])) 
			{
				$sql = "SELECT * FROM notebook_user LEFT JOIN notebook ON notebook.nb_owner = notebook_user.nu_id WHERE nu_handle = :handle ";

				$cmd = \Yii::$app->db->createCommand($sql);
				$cmd->bindValue(":handle", $_POST['nu_handle'], PDO::PARAM_STR);	
				
				$data = $cmd->queryOne();
				
				if (!empty($data['nu_id']))
				{
					self::encryptMessage($_POST['pg_content'],$_POST['pg_title'],$data['nu_pub'],$data['nu_id']);
				}
				else
				{
					die('0');
				}				
			}
			break;
			
			case "login":
			$cmd = \Yii::$app->db->createCommand("SELECT * FROM notebook_user WHERE nu_email = :email LIMIT 1");
			$cmd->bindValue(":email",$_POST['nu_email'],PDO::PARAM_STR);
			
			$data = $cmd->queryOne();
			
			if (\Yii::$app->getSecurity()->validatePassword($_POST['nu_password'],$data['nu_password'])) 
			{
				unset($data['nu_password']);
				\Yii::$app->session['logged_in'] = $data;
				header("Content-Type: Application/JSON");
				die(json_encode(\Yii::$app->db->createCommand("SELECT * FROM notebook_page ")->queryAll()));
				
			} 
			else 
			{
				die("0");
			}			
			break;
			
			case "get_notes":
			die(json_encode(\Yii::$app->db->createCommand("SELECT * FROM notebook_page WHERE pg_owner = ".
				intval(\Yii::$app->session['logged_in']['nu_id']))->queryOne())
			);
			break;
		}
	}
	public static function encryptMessage($message,$title = '',$pub,$nu_id)
	{
		openssl_public_encrypt($message,$encrypted,$pub);
		/**
		 * Store encrypted message in DB
		*/
		$sql = "INSERT INTO notebook_page (pg_notebook_id,pg_title, pg_content, pg_created,pg_updated,pg_owner) VALUES (0,:title, :crypto, :today, :now, :owner)";

		$cmd = \Yii::$app->db->createCommand($sql);
		$cmd->bindValue(":owner",  $nu_id, 						PDO::PARAM_INT);
		$cmd->bindValue(":title",  $title, 						PDO::PARAM_STR);
		$cmd->bindValue(":crypto", base64_encode($encrypted), 	PDO::PARAM_STR);
		$cmd->bindValue(":today",  date('Y-m-d H:i:s'), 		PDO::PARAM_STR);
		$cmd->bindValue(":now",    date('Y-m-d H:i:s'), 		PDO::PARAM_STR);

		$cmd->execute();
		
		unset($message);
		
		die("$encrypted<br>$pub<br>$nu_id");
	}
	public static function decryptMessage($pg_id,$private_key)
	{
		$encrypted = \Yii::$app->db->createCommand("SELECT pg_content FROM notebook_page 
		
		WHERE  pg_id = ".intval($pg_id)." 
		AND pg_owner = ".intval(\Yii::$app->session['logged_in']['nu_id'])." LIMIT 1")->queryOne();
		
		if (!empty($encrypted) && !empty($private_key))
		{
			$pkey = openssl_pkey_get_private($private_key);
			
			openssl_private_decrypt(base64_decode($encrypted['pg_content']), $decrypted, $pkey);
			
			return $decrypted;
		}
		return false;
	}
	public function actionListHandles()
	{
	}
	public function actionIndex()
	{
		return $this->render("home");
	}
	public function actionAddAttachment()
	{
		return $this->render('add-attachment');
	}

	public function actionAddNotebook()
	{
		return $this->render('add-notebook');
	}

	public function actionDelete()
	{
		return $this->render('delete');
	}

	public function actionLock()
	{
		return $this->render('lock');
	}

	public function actionUnlock()
	{
		return $this->render('unlock');
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
	public function actionEndSession()
	{
		unset(\Yii::$app->session['logged_in']);
		
		$session = \Yii::$app->session;
		$session->close();
		$session->destroy();
		return $this->render("index");
	}
	public function actionRegister()
	{
		return $this->render("register");
	}
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);


?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>

<link rel="stylesheet" href="/mvc/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/mvc/jquery-ui/jquery-ui.min.css">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
<style>
.gold{
color:#ffe901;
}
.green{
color:#0f3;
}
.align-right{
	text-align:right;
}
.delete{
	color:#f02;
}
.decrypt-cipher{
padding: 10px;
    width: 100%;
    font-family: monospace,'lucida console','courier new',fixedwidth;
    font-size: 13px;
    line-height: 13px;
    color: rgba(77, 77, 77, 0.9);
    text-shadow: 0 0 5px #fff;
    background: rgba(217, 217, 217, 0.8);
}
</style>
	</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => '<span class="fa fa-lock green"></span> Notebook',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'My Notes', 'url' => ['/notebook/my-notes']],
            ['label' => 'Send a note', 'url' => ['/notebook/add-note']],
            ['label' => 'Register', 'url' => ['/site/register']],
            empty(\Yii::$app->session['logged_in']['nu_email']) ? (
                ['label' => 'Login', 'url' => ['/notebook/my-notes']]
            ) : (
                ['label' => 'Logout', 'url' => ['/site/end-session']]
            ),/*
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            ) */
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Notebook <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>
<pre><?php // print_r($_SERVER); ?></pre>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>